# fly.toml app configuration file generated for servisne-info on 2024-03-13T21:47:41+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'servisne-info'
primary_region = 'otp'
console_command = '/rails/bin/rails console'

[build]

[deploy]
  release_command = './bin/rails db:prepare'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/rails/public'
  url_prefix = '/'

[processes]
  web = "bin/rails fly:server"
  cron = "supercronic /app/crontab"

[[services]]
  processes = ["web"]
