default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: servisne_info_development
  host: database
  username: developer
  password: developer

test:
  <<: *default
  database: servisne_info_test
  host: database
  username: developer
  password: developer

production:
  <<: *default
  database: servisne_info_production
  username: servisne_info
  password: <%= ENV['SERVISNE_INFO_DATABASE_PASSWORD'] %>
