x-app: &app
  build:
    context: .
    args:
      RUBY_VERSION: '3.2.1'
  image: servisne_info:1.0.0
  environment: &env
    RAILS_ENV: ${RAILS_ENV:-development}
  tmpfs:
    - /tmp
    - /app/tmp/pids

x-backend: &backend
  <<: *app
  stdin_open: true
  tty: true
  volumes:
    - ..:/app:cached
    - bundle:/usr/local/bundle
    - rails-cache:/app/tmp/cache
    - si-ssh-data:/ssh:ro
  environment: &backend_environment
    <<: *env
    MALLOC_ARENA_MAX: 2
    WEB_CONCURRENCY: ${WEB_CONCURRENCY:-1}
    BOOTSNAP_CACHE_DIR: /usr/local/bundle/_bootsnap
    XDG_DATA_HOME: /app/tmp/cache
    SSH_AUTH_SOCK: /ssh/auth/sock
  depends_on: &backend_depends_on
    database:
      condition: service_healthy

services:
  rails:
    <<: *backend
    command: bundle exec rails

  web:
    <<: *backend
    command: bundle exec rails server -b 0.0.0.0
    ports:
      - '3000:3000'

  database:
    image: postgres:12
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: developer
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "/var/run/postgresql", "-U", "developer"]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  bundle:
  rails-cache:
  postgres-data:
  si-ssh-data:
    name: servisne_info_ssh_data
